name: Daily IT Learning Content Post

on:
  schedule:
    # 毎日 日本時間 午前9時に実行 (UTC 0時 = JST 9時)
    # 月曜日〜金曜日のみ実行
    - cron: '0 0 * * 1,3,5'
  workflow_dispatch: # 手動実行も可能

jobs:
  auto-post:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv
    
    - name: Run production auto post script
      env:
        CHATWORK_API_TOKEN: ${{ secrets.CHATWORK_API_TOKEN }}
        CHATWORK_ROOM_ID: ${{ secrets.CHATWORK_ROOM_ID }}
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        TZ: 'Asia/Tokyo'
      run: python enhanced_auto_post_production.py
